import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="relative min-h-screen">
          <div
            className="fixed inset-0 -z-10 bg-center bg-no-repeat"
            style={{
              backgroundImage: "url('/backgrounds/pinkMarble.jpg')",
              backgroundSize: "cover",
              backgroundAttachment: "fixed",
              backgroundColor: "#f7f2f4",
            }}
          />
          {children}
        </div>
      </body>
    </html>
  );
}
